apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T11:16:36Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "901"
  uid: a59470ee-34a4-475d-a85c-f46b7b2886a0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.220.59
  clusterIPs:
  - 10.110.220.59
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30597
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
